### ISSUE TITLE
python3 以及有秒杀价的时候运行会造成 index out of range

### ISSUE THREAD

**Issue by HonorWater** [jackleeforce/price_monitor#1]
首先感谢提供了势力，很方便就运行成功。
在python 2.7环境下没有问题，但是到了python3的环境下就会频繁报index out of range
应该是 for 循环没有做对应的越界处理

**Comment by HonorWater** [comment]
current_price = selector.xpath('//span[@id="priceblock_ourprice"]/text()')[0]
IndexError: list index out of range
2019-11-22 09:31:43-root-Something wrong,retry count:0

**Comment by numgao** [comment]
current_price = (selector.xpath('//span[@id="priceblock_dealprice"]/text()')[0]).strip()
改成上面这样的 就不会有报警了 不知道对不对

**Comment by jackleeforce** [comment]
@HonorWater  奇怪，我这边python3没发现这个问题，倒是发现了在秒杀价或者关注的商品缺货的时候，就会报错，我排查下。
